my_urlread('https://s3.amazonaws.com/maxwell-in', 'post', ...
    {'key', 'thetestfilefromMatlab', ...
    'acl', 'public-read', ...
    'content-type', 'application/octet-stream', ...
    'AWSAccessKeyId', 'AKIAI6BMVTBFEAMEMHQQ', ...
    'policy', 'ewogICJleHBpcmF0aW9uIjogIjIwMjAtMDEtMDFUMTI6MDA6MDAuMDAwWiIsCiAgImNvbmRpdGlvbnMiOiBbCiAgICB7ImJ1Y2tldCI6ICJtYXh3ZWxsLWluIiB9LAogICAgeyJhY2wiOiAicHVibGljLXJlYWQiIH0sCiAgICBbInN0YXJ0cy13aXRoIiwgIiRrZXkiLCAiIl0sCiAgICBbInN0YXJ0cy13aXRoIiwgIiRDb250ZW50LVR5cGUiLCAiYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtIl0sCiAgXQp9Cg==', ...
    'signature', 'QEPdrd7W6aOG8yO/tMOeyWWeNFY=', ...
    'file', 'hihihi'}, ...
    1);
% <input type="text" name="key" value="testfile.txt" />
% <input type="text" name="acl" value="public-read" />
% <input type="text" name="content-type" value="application/octet-stream" />
% <input type="hidden" name="AWSAccessKeyId" value="AKIAI6BMVTBFEAMEMHQQ" />
% <input type="hidden" name="policy" value="ewogICJleHBpcmF0aW9uIjogIjIwMjAtMDEtMDFUMTI6MDA6MDAuMDAwWiIsCiAgImNvbmRpdGlvbnMiOiBbCiAgICB7ImJ1Y2tldCI6ICJtYXh3ZWxsLWluIiB9LAogICAgeyJhY2wiOiAicHVibGljLXJlYWQiIH0sCiAgICBbInN0YXJ0cy13aXRoIiwgIiRrZXkiLCAiIl0sCiAgICBbInN0YXJ0cy13aXRoIiwgIiRDb250ZW50LVR5cGUiLCAiYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtIl0sCiAgXQp9Cg==" />
% <input type="hidden" name="signature" value="QEPdrd7W6aOG8yO/tMOeyWWeNFY=" />
% <input name="file" type="file" />
